"use client";

import { useState, useEffect } from "react";
import Image from "next/image";
import { useGenerateContext } from "./GenerateContext";
import { CAREER_ROLES } from "@/lib/ambitionsData";
import { useRouter } from "next/navigation";

export default function StepSix() {
  const router = useRouter();
  const { 
    selectedCareer, selectedAttire, 
    selectedProduct, setSelectedProduct,
    isDownloading, setIsDownloading,
    isOrderPlaced, setIsOrderPlaced,
    deliveryName, deliveryPhone, deliveryAddress,
    setUploadedImage
  } = useGenerateContext();

  const [orderId, setOrderId] = useState("");
  useEffect(() => {
    setOrderId(`FF-${Math.floor(10000 + Math.random() * 90000)}`);
  }, []);

  const careerObj = selectedCareer ? CAREER_ROLES[selectedCareer] : null;
  
  if (!careerObj) {
    return (
      <div className="w-full flex items-center justify-center p-12 text-slate-500 font-sans">
        Please select a career role first.
      </div>
    );
  }

  const attireObj = careerObj.attireVariations?.find(a => a.id === selectedAttire);

  const handleSimulateDownload = () => {
    setIsDownloading(true);
    setTimeout(() => {
      setIsDownloading(false);
      alert("Download completed!");
    }, 2000);
  };

  const handleRemoveImage = () => {
    setUploadedImage(null);
    router.push("?step=1");
  };

  return (
    <div className="w-full flex flex-col gap-8 sm:gap-12 animate-fade-in pb-16">
      
      {/* Header section with brand titles to match Figma screenshot */}
      <div className="flex flex-col items-start w-full text-left">
        <h1 className="font-sans font-bold text-[38px] sm:text-[44px] leading-[1.05] tracking-[-0.04em] text-[#000000]">
          Pick the dream ambition
        </h1>
        <p className="font-sans font-normal text-[16px] sm:text-[18px] leading-none tracking-[-0.03em] text-[#64748B] mt-2">
          100+ careers across 13 categories.
        </p>
      </div>

      {/* Two-Column Showcase Layout */}
      <div className="flex flex-col lg:flex-row gap-8 lg:gap-12 lg:items-center items-start mt-4 justify-start">
        
        {/* Left Column: Large Vertical Preview Card with overlay buttons */}
        <div className="flex flex-col items-center lg:items-start gap-6 shrink-0 w-full lg:w-auto">
          
          {/* Photo Frame Container with exact Figma dimensions and responsive behavior */}
          <div 
            className="relative w-full max-w-[449.8px] aspect-[449.8/605] lg:aspect-auto lg:w-[449.8px] lg:h-[605px] rounded-[23.48px] overflow-hidden border border-slate-100 shadow-[0_15px_40px_-5px_rgba(0,0,0,0.06)] flex flex-col justify-end shrink-0"
          >
            
            {/* The generated professional career portrait */}
            <div className="absolute inset-0 w-full h-full">
              <Image
                src={careerObj.imageSrc}
                alt={careerObj.title}
                fill
                className="object-cover"
                priority
              />
              
              {/* Smooth professional gradient blend at the bottom */}
              <div className="absolute inset-0 bg-gradient-to-t from-black/25 via-transparent to-transparent pointer-events-none" />
            </div>

            {/* Double Overlay Action Buttons at Bottom-Right */}
            <div className="absolute bottom-6 right-6 z-20 flex items-center gap-3">
              
              {/* WhatsApp Lime-Green button */}
              <a
                href={`https://api.whatsapp.com/send?text=Check out my child's future ambition as a ${careerObj.title} generated by Ambition!`}
                target="_blank"
                rel="noopener noreferrer"
                className="bg-[#8CE827] hover:bg-[#7cd01f] text-white rounded-[12px] w-[52px] h-[52px] flex items-center justify-center cursor-pointer shadow-lg transition-all hover:scale-105 active:scale-95"
                title="Share on WhatsApp"
              >
                <Image
                  src="/assets/icons/whatsapp_logo.svg"
                  alt="WhatsApp logo"
                  width={32}
                  height={32}
                  className="object-contain"
                />
              </a>

              {/* Retry/Reload circular-arrow button */}
              <button
                onClick={handleRemoveImage}
                className="bg-[#FFFFFF] hover:bg-slate-50 text-black border border-slate-200 rounded-[12px] w-[52px] h-[52px] flex items-center justify-center cursor-pointer shadow-lg transition-all hover:scale-105 active:scale-95"
                title="Start over"
              >
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#000000" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M21.5 2v6h-6M21.34 15.57a10 10 0 1 1-.57-8.38l5.67-5.67" />
                </svg>
              </button>

            </div>
          </div>

        </div>

        {/* Right Column: Product E-Commerce Selector */}
        <div className="w-full lg:w-[821px] flex flex-col gap-6 shrink-0">
          
          {/* 2x2 Grid of Selectable Product Cards */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-[17px] w-full max-w-[821px]">
            
            {/* Card 1: Wall poster with frame */}
            <div
              onClick={() => setSelectedProduct("wall")}
              className={`flex items-center gap-[15px] bg-[#FFFFFF] rounded-[17.7px] p-[10.6px] cursor-pointer transition-all duration-300 hover:scale-[1.01] hover:shadow-md w-full sm:w-[402px] h-[143px] border-[1.18px] ${
                selectedProduct === "wall"
                  ? "border-[#561DFF] shadow-[0_4px_20px_rgba(86,29,255,0.15)]"
                  : "border-[#D0D0D0]"
              }`}
            >
              {/* Left mockup: Frame on wall */}
              <div className="w-[119px] h-[119px] rounded-[14px] overflow-hidden shrink-0 relative border border-slate-100/50 shadow-sm">
                <Image
                  src="/assets/images/new/frame_1.jpg"
                  alt="Wall poster with frame mockup"
                  fill
                  className="object-cover"
                  sizes="119px"
                  priority
                />
              </div>
              
              {/* Details Content */}
              <div className="flex flex-col justify-center items-start h-full py-1">
                <h3 className="font-sans font-bold text-[18px] text-[#000000] tracking-tight leading-tight mb-[5px]">
                  Wall poster with frame
                </h3>
                <p className="font-sans font-normal text-[13px] text-[#64748B] tracking-tight leading-tight mb-[12px]">
                  Perfect for the walls
                </p>
                {/* Price Badge */}
                <div className="font-sans font-bold text-[15.5px] text-white bg-[#561DFF] px-[23px] py-[8.8px] rounded-[8.8px] select-none leading-none">
                  ₹299
                </div>
              </div>
            </div>

            {/* Card 2: Table Frame */}
            <div
              onClick={() => setSelectedProduct("table")}
              className={`flex items-center gap-[15px] bg-[#FFFFFF] rounded-[17.7px] p-[10.6px] cursor-pointer transition-all duration-300 hover:scale-[1.01] hover:shadow-md w-full sm:w-[402px] h-[143px] border-[1.18px] ${
                selectedProduct === "table"
                  ? "border-[#561DFF] shadow-[0_4px_20px_rgba(86,29,255,0.15)]"
                  : "border-[#D0D0D0]"
              }`}
            >
              {/* Left mockup: standing photo frame on desk */}
              <div className="w-[119px] h-[119px] rounded-[14px] overflow-hidden shrink-0 relative border border-slate-100/50 shadow-sm">
                <Image
                  src="/assets/images/new/frame_2.jpg"
                  alt="Table Frame mockup"
                  fill
                  className="object-cover"
                  sizes="119px"
                  priority
                />
              </div>
              
              {/* Details Content */}
              <div className="flex flex-col justify-center items-start h-full py-1">
                <h3 className="font-sans font-bold text-[18px] text-[#000000] tracking-tight leading-tight mb-[5px]">
                  Table Frame
                </h3>
                <p className="font-sans font-normal text-[13px] text-[#64748B] tracking-tight leading-tight mb-[12px]">
                  Perfect for the study desk
                </p>
                {/* Price Badge */}
                <div className="font-sans font-bold text-[15.5px] text-white bg-[#561DFF] px-[23px] py-[8.8px] rounded-[8.8px] select-none leading-none">
                  ₹299
                </div>
              </div>
            </div>

            {/* Card 3: Frameless poster */}
            <div
              onClick={() => setSelectedProduct("frameless")}
              className={`flex items-center gap-[15px] bg-[#FFFFFF] rounded-[17.7px] p-[10.6px] cursor-pointer transition-all duration-300 hover:scale-[1.01] hover:shadow-md w-full sm:w-[402px] h-[143px] border-[1.18px] ${
                selectedProduct === "frameless"
                  ? "border-[#561DFF] shadow-[0_4px_20px_rgba(86,29,255,0.15)]"
                  : "border-[#D0D0D0]"
              }`}
            >
              {/* Left mockup: frameless poster */}
              <div className="w-[119px] h-[119px] rounded-[14px] overflow-hidden shrink-0 relative border border-slate-100/50 shadow-sm">
                <Image
                  src="/assets/images/new/frame_3.jpg"
                  alt="Frameless poster mockup"
                  fill
                  className="object-cover"
                  sizes="119px"
                  priority
                />
              </div>
              
              {/* Details Content */}
              <div className="flex flex-col justify-center items-start h-full py-1">
                <h3 className="font-sans font-bold text-[18px] text-[#000000] tracking-tight leading-tight mb-[5px]">
                  Frameless poster
                </h3>
                <p className="font-sans font-normal text-[13px] text-[#64748B] tracking-tight leading-tight mb-[12px]">
                  Perfect for the study desk
                </p>
                {/* Price Badge */}
                <div className="font-sans font-bold text-[15.5px] text-white bg-[#561DFF] px-[23px] py-[8.8px] rounded-[8.8px] select-none leading-none">
                  ₹299
                </div>
              </div>
            </div>

            {/* Card 4: Acrylic Frame */}
            <div
              onClick={() => setSelectedProduct("acrylic")}
              className={`flex items-center gap-[15px] bg-[#FFFFFF] rounded-[17.7px] p-[10.6px] cursor-pointer transition-all duration-300 hover:scale-[1.01] hover:shadow-md w-full sm:w-[402px] h-[143px] border-[1.18px] ${
                selectedProduct === "acrylic"
                  ? "border-[#561DFF] shadow-[0_4px_20px_rgba(86,29,255,0.15)]"
                  : "border-[#D0D0D0]"
              }`}
            >
              {/* Left mockup: high-gloss acrylic block */}
              <div className="w-[119px] h-[119px] rounded-[14px] overflow-hidden shrink-0 relative border border-slate-100/50 shadow-sm">
                <Image
                  src="/assets/images/new/frame_4.jpg"
                  alt="Acrylic Frame mockup"
                  fill
                  className="object-cover"
                  sizes="119px"
                  priority
                />
              </div>
              
              {/* Details Content */}
              <div className="flex flex-col justify-center items-start h-full py-1">
                <h3 className="font-sans font-bold text-[18px] text-[#000000] tracking-tight leading-tight mb-[5px]">
                  Acrylic Frame
                </h3>
                <p className="font-sans font-normal text-[13px] text-[#64748B] tracking-tight leading-tight mb-[12px]">
                  Perfect for the study desk
                </p>
                {/* Price Badge */}
                <div className="font-sans font-bold text-[15.5px] text-white bg-[#561DFF] px-[23px] py-[8.8px] rounded-[8.8px] select-none leading-none">
                  ₹299
                </div>
              </div>
            </div>

          </div>

          {/* Muted Disclaimer Text */}
          <p className="font-sans font-normal text-[13px] sm:text-[14px] text-[#64748B] mt-2 select-none">
            *We ship all Across India (Shipping charges may vary based on location)
          </p>

          {/* Action Buttons Column */}
          <div className="flex flex-col gap-3 w-full mt-4 select-none">
            
            <button
              onClick={() => alert("Proceeding to payment gateway...")}
              className="w-full max-w-[821px] lg:w-[821px] h-[72px] rounded-[11px] bg-[#561DFF] hover:bg-[#4512e0] text-white font-sans font-semibold text-[18px] tracking-tight py-[15px] px-[31.5px] gap-[15px] hover:scale-[1.01] active:scale-[0.99] transition-all duration-300 shadow-md cursor-pointer flex items-center justify-center"
            >
              <span>Continue to checkout</span>
            </button>

            {/* Secondary Button: Download the frame for free */}
            <button
              onClick={handleSimulateDownload}
              disabled={isDownloading}
              className="w-full max-w-[821px] lg:w-[821px] h-[72px] rounded-[11px] bg-[#000000] hover:bg-black/90 text-white font-sans font-semibold text-[18px] tracking-tight py-[15px] px-[31.5px] gap-[15px] hover:scale-[1.01] active:scale-[0.99] transition-all duration-300 shadow-md cursor-pointer flex items-center justify-center disabled:opacity-75 disabled:pointer-events-none"
            >
              {isDownloading ? (
                <>
                  <svg className="animate-spin h-5 w-5 text-white" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                  </svg>
                  <span>Preparing download...</span>
                </>
              ) : (
                <span>Download the frame for free</span>
              )}
            </button>

          </div>

        </div>

      </div>


      {/* Confetti / Order Success Overlay Modal */}
      {isOrderPlaced && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-6 animate-fade-in">
          <div className="bg-[#FFFFFF] rounded-[24px] border border-slate-100 p-8 sm:p-10 max-w-[540px] w-full text-center relative shadow-2xl flex flex-col items-center animate-scale-up">
            
            {/* Confetti fallers */}
            <div className="absolute inset-0 pointer-events-none overflow-hidden rounded-[24px]">
              <div className="confetti absolute w-2.5 h-2.5 bg-[#5C17EC] rounded-full left-[15%] top-[-10px] animate-confetti-fall" style={{ animationDelay: '0.1s' }} />
              <div className="confetti absolute w-2 h-3 bg-[#FF3E6C] left-[35%] top-[-10px] animate-confetti-fall" style={{ animationDelay: '0.3s' }} />
              <div className="confetti absolute w-3 h-2 bg-[#0091FF] left-[55%] top-[-10px] animate-confetti-fall" style={{ animationDelay: '0s' }} />
              <div className="confetti absolute w-2 h-2 bg-[#FFAB00] rounded-full left-[75%] top-[-10px] animate-confetti-fall" style={{ animationDelay: '0.5s' }} />
              <div className="confetti absolute w-2.5 h-3.5 bg-[#10B981] left-[90%] top-[-10px] animate-confetti-fall" style={{ animationDelay: '0.2s' }} />
            </div>

            {/* Success Checkmark Circle */}
            <div className="w-[72px] h-[72px] rounded-full bg-[#ECFDF5] border-[3px] border-[#10B981] flex items-center justify-center text-[#10B981] mb-6 shadow-sm">
              <svg width="34" height="34" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                <polyline points="20 6 9 17 4 12" />
              </svg>
            </div>

            <h3 className="font-sans font-bold text-[28px] text-[#000000] mb-2 leading-none">
              Order Placed Successfully!
            </h3>
            <p className="font-sans font-semibold text-[15px] text-[#10B981] mb-6">
              Order ID: {orderId || "FF-10020"}
            </p>

            <p className="font-sans font-medium text-[15px] text-[#64748B] leading-relaxed mb-8 max-w-[400px]">
              Thank you! We have received your order for the personalized <strong>
                {selectedProduct === "wall" ? "Wall poster with frame" :
                 selectedProduct === "table" ? "Table Frame" :
                 selectedProduct === "frameless" ? "Frameless poster" :
                 "Acrylic Frame"}
              </strong> under the <strong>{careerObj.title} ({attireObj?.name})</strong> career.
            </p>

            {/* Receipt breakdown */}
            <div className="bg-[#F8FAFC] border border-[#E2E8F0] rounded-[16px] p-5 w-full flex flex-col gap-2.5 mb-8 select-none text-[14px]">
              <div className="flex justify-between text-slate-600 font-medium">
                <span>Recipient Name</span>
                <span className="text-black font-bold">{deliveryName}</span>
              </div>
              <div className="flex justify-between text-slate-600 font-medium">
                <span>Contact Mobile</span>
                <span className="text-black font-bold">{deliveryPhone}</span>
              </div>
              <div className="flex justify-between text-slate-600 font-medium text-left">
                <span className="shrink-0 w-24">Ship Address</span>
                <span className="text-black font-bold truncate max-w-[280px]" title={deliveryAddress}>{deliveryAddress}</span>
              </div>
              <div className="flex justify-between text-slate-800 font-bold border-t border-slate-200 pt-2.5 text-[15px] mt-0.5">
                <span>Grand Total (COD)</span>
                <span className="text-black">₹299</span>
              </div>
            </div>

            {/* Actions */}
            <div className="flex flex-col sm:flex-row gap-3 w-full">
              <button
                onClick={() => setIsOrderPlaced(false)}
                className="flex-1 border border-slate-200 rounded-full h-[48px] font-sans font-semibold text-[14px] hover:bg-slate-50 active:scale-98 transition-all duration-300 cursor-pointer"
              >
                Close Window
              </button>
              <button
                onClick={handleRemoveImage}
                className="flex-1 bg-black text-white rounded-full h-[48px] font-sans font-semibold text-[14px] hover:bg-black/90 active:scale-98 transition-all duration-300 cursor-pointer"
              >
                Back to Home
              </button>
            </div>

          </div>
        </div>
      )}

    </div>
  );
}
